Caso de Uso 33
surullisuus/prototipos-repo pull request #29
Opened 2024-07-11 22:41 UTC by dm73994

2024-07-15 21:12 UTC, surullisuus requested changes
fix: arreglar el tamaño de la pantalla de consultar seguimiento de notificaciones,ya que los inputs se salen del tamaño del menú superior
fix:arreglar el estilo del botón limpiar,ya que no debe ser de ese color y no debe estar relleno
fix:intentar arreglar la distribución de la tabla en consultar seguimiento de notificaciones
fix:en acuse recibo cambiar  "casual" por CAUSAL y cambiar el estilo del botón cancelar a como está en las anteriores pantallas
fix: corregir las HU 3 y 4,ya que la pantalla 4 sale al dar click en la opción Asociar de la pantalla que describe la HU 3

2024-07-17 01:36 UTC, dm73994 commented
fix: arreglar el tamaño de la pantalla de consultar seguimiento de notificaciones,ya que los inputs se salen del tamaño del menú superior
fix:arreglar el estilo del botón limpiar,ya que no debe ser de ese color y no debe estar relleno
fix:en acuse recibo cambiar "casual" por CAUSAL y cambiar el estilo del botón cancelar a como está en las anteriores pantallas
fix: corregir las HU 3 y 4,ya que la pantalla 4 sale al dar click en la opción Asociar de la pantalla que describe la HU 3

2024-07-17 16:12 UTC, surullisuus requested changes
fix: arreglas app.module y app.routes

2024-07-17 17:25 UTC, surullisuus approved these changes

2024-07-17 17:31 UTC, merged