feat/dm/Carpeta 42 HU 1: Flujo de gestión del documento
surullisuus/prototipos-repo pull request #48
Opened 2024-08-05 15:58 UTC by dm73994

2024-08-05 17:02 UTC, surullisuus requested changes
fix: vista enviar firma el tipo debe ser titulo tipo debe ser tipo documental segun la HU
fix: el label que dice elaborado debe cambiarse por Elaboró
fix: el label que dice Responsable debe cambiarse por Responsable firma
fix: en enviar firma deben ir 3 labels que deben estar en disabled con Responsable firma,responsable aprobación y responsable revisión
fix: faltan las vistas de aprobación y revisión

2024-08-06 01:52 UTC, dm73994 commented
fix: Las vistas las separe por botones que envían un estado diferente al documento lo cual hace el cambio de vistas, por eso puse 3 botones: 
![image](https://github.com/user-attachments/assets/118d1baa-5a69-4b71-bf4b-cb7b82401d77)

fix: se ajustó el nombre de cada etiqueta

fix: los componentes deshabilitados cambian segun en el estado que esté el documento

2024-08-06 16:15 UTC, surullisuus requested changes
fix: app.module y app.routes para hacer el merge
fix: los labels que solo son Responsable* colocarlo como responsable revisión

2024-08-07 15:04 UTC, surullisuus approved these changes

2024-08-07 15:05 UTC, merged