feat/dm/correcciones
surullisuus/prototipos-repo pull request #51
Opened 2024-09-16 01:36 UTC by dm73994

se ajustaron en base al excel las siguientes HU: 
1. SISFV-TRAN-HU_Lista de usuarios del Grupo_Subdirección (CU014)_v1.0
2. SISFV-TRAN-HU_Iniciar tarea (CU040)_v1.0
3. SISFV-TRAN-HU_EliminarTiposDocumentalesProcesos (CU022)_v1.0
4. SISFV-TRAN-HU_AcuseRecibo (CU042)
5. SISFV-TRAN-HU_Filtros de busqueda - TiposDocumentalesProcesos (CU022)_v1.0

Quedan pendientes algunas porque no tengo acceso a las historias de usuario y no puedo ver que hay que corregir

2024-09-16 17:58 UTC, surullisuus requested changes
fix: en la tabla de Tareas sugeridas el modal de Aprobar y rechazar no están
fix: en tabla tareas actuales el icono de el ícono del estatus temporal (el triángulo) está muy separado del estatus. Arreglar ordenación por filas ascendente y descendente de las tablas.
fix: en configuracion de tipos documentales los botones buscaar guardar y cancelar no corresponden con los colores que deben llevar
fix: en acuse recibido acomodar los botones en los estilos que corresponden y campos obligatorios,no debe dejar guardar si no se han llenado

fix: qué se acomodó de los filtros de búsqueda del CU 22?

PEDIR ACCESO A LA CARPETA O PREGUNTAR A COMPAÑEROS QUE YA TIENEN EL ACCESO O EL ZIP DE LAS HU

FIX GENERAL: revisar cada HU y si tiene filtros de búsqueda y tablas que muestren la infromación,agregar ordenacion ascendente y descentente para cada columna . Si hay formularios o paginas que requieran campos obligatorios,no debe dejar enviar o guardar sin haber llenado esos campos obligatorios,deben colocarse en rojo o por defecto salir un modal de que hubo un error porque no se han llenado los campos requeridos

2024-09-17 04:59 UTC, surullisuus requested changes
fix: al dar click en asignar redirecciona bien a asignar responsable tarea,pero cuando le doy en el botón cancelar,no me redirecciona a la anterior pantalla
fix: En configurar tipos documentales, el botón cancelar no puede tener el mismo estilo del guardar, revisar icnonografía del govco. La tabla de los registros debe salir por defecto si no se ha seleccionado ningún filtro de búsqueda. Falta prototipar el mensaje de no existen registros o coincidencias cuando se selecciona algún filtro y no existe un registro con esas características.
fix: CU 42 en el acuse recibido,los colores de los botones siguen mal,el guardar y el cancelar no pueden tener el mismo color. También la fecha acuse de recibido es obligatoria pero no se puede llenar ,por lo tanto no debería dejar habilitar el botón de guardar.
fix: faltan los campos obligatorios y ordenamiento en las demás HU trabajadas,así mismo como el prototipado del mensaje de que no se encontraron coincidencias. Se puede filtrar por un sólo input o select, no es necesario llenar todos.
fix: http://localhost:4200/#/gestionar-proceso-diseno al asociar un documento de entrada y dar en ver radicado se bugea
fix: arreglar app.routes y app.module

2024-09-17 17:25 UTC, dm73994 commented
fix: http://localhost:4200/#/gestionar-proceso-diseno al asociar un documento de entrada y dar en ver radicado se bugea

esa vista no la he trabajado yo

2024-09-17 18:21 UTC, surullisuus requested changes
fix: la recomendación del botón buscar y el cancelar
fix: el modal de buscar coincidencias no está bien,puedes dejarlo por el momento así para aceptar el PR,pero igual tienes que cambiarlo.
el mensaje debe aparecer en la tabla como no se encontraron registros

2024-09-18 06:32 UTC, surullisuus requested changes
fix: app.route y app.module

2024-09-18 18:46 UTC, surullisuus approved these changes
fix: el botón nunca se acomodó con los estilos correctos,se acomodará desde main

2024-09-18 18:47 UTC, merged